<a href="https://colab.research.google.com/github/pratibha010/pythoncolab11/blob/main/diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
import pandas as pd

df = pd.read_csv("diabetes.csv")

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
df.shape

(768, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.size

6912

In [ ]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
df.describe

<bound method NDFrame.describe of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]>

In [ ]:
df.isnull

<bound method DataFrame.isnull of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]>

In [ ]:
(df == 0).any()

Pregnancies                  True
Glucose                      True
BloodPressure                True
SkinThickness                True
Insulin                      True
BMI                          True
DiabetesPedigreeFunction    False
Age                         False
Outcome                      True
dtype: bool

In [ ]:
import numpy as np
invalid_zero_cols =['Glucose', 'BloodPressure' ,'SkinThickness','Insulin','BMI']

df[invalid_zero_cols] =  df[invalid_zero_cols].replace(0,np.nan)

In [ ]:
for col in invalid_zero_cols:
  df[col].fillna(df[col].median(),inplace=True)

/tmp/ipython-input-2659693362.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)


In [ ]:
#feature target separation
#feature
x = df.drop(columns = ['Outcome'])
#target
y = df['Outcome']

In [ ]:
x.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [ ]:
y.name

'Outcome'

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape,x_test.shape

((614, 8), (154, 8))

In [ ]:
y.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
y_train.value_counts()

Outcome
0    401
1    213
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

Outcome
0    99
1    55
Name: count, dtype: int64

In [ ]:
y_train.value_counts(normalize=True)

Outcome
0    0.653094
1    0.346906
Name: proportion, dtype: float64

In [ ]:
from sklearn.preprocessing  import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train_scaled,y_train)

LogisticRegression()

In [ ]:
y_pred = log_reg.predict(x_test_scaled)

In [ ]:
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
log_reg.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
log_reg.score(x_train_scaled,y_train)

0.7703583061889251

In [ ]:
log_reg.score(x_train_scaled,y_train)

0.7703583061889251

In [ ]:
# linear regrassion probability prediction
y_prob = log_reg.predict_proba(x_test_scaled)

In [ ]:
y_prob[:20]

array([[0.72650648, 0.27349352],
       [0.83274552, 0.16725448],
       [0.89278831, 0.10721169],
       [0.84589992, 0.15410008],
       [0.53748186, 0.46251814],
       [0.56562556, 0.43437444],
       [0.98601508, 0.01398492],
       [0.6160686 , 0.3839314 ],
       [0.4244803 , 0.5755197 ],
       [0.23804933, 0.76195067],
       [0.77764247, 0.22235753],
       [0.10709486, 0.89290514],
       [0.62464797, 0.37535203],
       [0.72006814, 0.27993186],
       [0.92184111, 0.07815889],
       [0.59630803, 0.40369197],
       [0.88761243, 0.11238757],
       [0.92622869, 0.07377131],
       [0.27479951, 0.72520049],
       [0.42204828, 0.57795172]])

In [ ]:
y_prob_diabetic = y_prob[:,1]
y_prob_diabetic[:10]

array([0.27349352, 0.16725448, 0.10721169, 0.15410008, 0.46251814,
       0.43437444, 0.01398492, 0.3839314 , 0.5755197 , 0.76195067])

In [ ]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm
#[TN FP]
#[FN TP]

#TN - true negative - actually non diabetic
#FP - false positive - actually non diabetic but predicted diabetic
#FN - false negative - actually diabetic but predicted non diabetic
#TP - true positive - actually diabetic

array([[82, 17],
       [21, 34]])

In [ ]:
from sklearn.metrics import classification_report
print ( classification_report(y_test,y_pred))



              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154



In [ ]:
y_pred_svm_model = log_reg.predict(x_test_scaled)


In [ ]:
log_reg.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
from sklearn.metrics import confusion_matrix
cm_svm=confusion_matrix(y_test,y_pred_svm_model)
cm_svm

array([[82, 17],
       [21, 34]])

In [ ]:
y_prob[:10]

array([[0.72650648, 0.27349352],
       [0.83274552, 0.16725448],
       [0.89278831, 0.10721169],
       [0.84589992, 0.15410008],
       [0.53748186, 0.46251814],
       [0.56562556, 0.43437444],
       [0.98601508, 0.01398492],
       [0.6160686 , 0.3839314 ],
       [0.4244803 , 0.5755197 ],
       [0.23804933, 0.76195067]])

In [ ]:
#confussion matrix
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
y_prob_svm = log_reg.predict_proba(x_test_scaled)
print("\nFirst 20 probability predictions from Logistic Regression model:")
print(y_prob_svm[:20])

              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154


First 20 probability predictions from Logistic Regression model:
[[0.72650648 0.27349352]
 [0.83274552 0.16725448]
 [0.89278831 0.10721169]
 [0.84589992 0.15410008]
 [0.53748186 0.46251814]
 [0.56562556 0.43437444]
 [0.98601508 0.01398492]
 [0.6160686  0.3839314 ]
 [0.4244803  0.5755197 ]
 [0.23804933 0.76195067]
 [0.77764247 0.22235753]
 [0.10709486 0.89290514]
 [0.62464797 0.37535203]
 [0.72006814 0.27993186]
 [0.92184111 0.07815889]
 [0.59630803 0.40369197]
 [0.88761243 0.11238757]
 [0.92622869 0.07377131]
 [0.27479951 0.72520049]
 [0.42204828 0.57795172]]


In [ ]:
y_prob_svm[:10]

array([[0.72650648, 0.27349352],
       [0.83274552, 0.16725448],
       [0.89278831, 0.10721169],
       [0.84589992, 0.15410008],
       [0.53748186, 0.46251814],
       [0.56562556, 0.43437444],
       [0.98601508, 0.01398492],
       [0.6160686 , 0.3839314 ],
       [0.4244803 , 0.5755197 ],
       [0.23804933, 0.76195067]])

In [ ]:
from sklearn.metrics import roc_auc_score

roc_auc_lr = roc_auc_score(y_test, y_prob_diabetic)
print(f"ROC AUC for Logistic Regression: {roc_auc_lr}")
# roc_auc_svm is not calculated as no SVM model was trained.

ROC AUC for Logistic Regression: 0.82277318640955
